version: '3'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
    command: ["npm", "run", "start"]
  mongo_db:
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"

volumes:
  db_data: {}